send_command:
  name: Send command
  description: Send device command through RFPlayer and create switch entity if needed.
  fields:
    command:
      name: Command
      description: The command to be sent.
      required: true
      example: "ON"
      selector:
        text:
    protocol:
      name: Protocol
      description: RFPlayer compatible protocol.
      required: true
      example: CHACON
      selector:
        text:
    device_address:
      name: Device address
      description: Device address.
      required: false
      example: A1
      selector:
        text:
    device_id:
      name: Device ID
      description: Device ID.
      required: false
      example: 40
      selector:
        text:
    automatic_add:
      name: Create entity
      description: Create associated switch entity
      required: true
      default: false
      selector:
        boolean:
